#!/usr/bin/env python

import sys
from geojson import loads
from uuid import uuid4
from couchdb import Server

name = sys.argv[1]
source = sys.argv[2]

server = Server('http://localhost:5984/')
if name in server:
    del server[name]
db = server.create(name)

print "loading '%s'"%source
collection = loads(file(source).read())
print "loaded %d features"%len(collection['features'])

for feature in collection['features']:
    id = uuid4().hex
    db[id] = {
        'type': 'Feature',
        'properties': dict([(k.lower(), v) for k,v in feature['properties'].iteritems()]),
        'geometry': feature['geometry']
    }

    print "feature insert '%s'"%id
